/* eslint-disable prettier/prettier */
export const state = {
  baharika: [
    'piperi-aspro',
    'piperi-mauro',
    'piperi-kokkino-gliko',
    'piperi-kokkino-kaytero', 
    'alati', 
    'kanela',
    'kanela trimeni', 
    'kari-kitrino',
    'kari-kokkino-kaytero',
    'fylla dafnis',
    'mpoukobo',
    'selino',
    'diosmos',
    'kimino',
    'glikaniso',
    'mpahari',
    'moustarda',
    'matzourana',
    'basilikos',
    'koliandros',
    'rigani',
    'paprika-glikia',
    'paprika-kayteri',
    'piperoriza',
    'piperoriza-trimeni',
    'tsili-kaytero',
    'tikka massala',
    'dendrolibano',
    'thimari',
    'trimpa',
    'skordo',
    'kremidi',
    'diasmos',
    'marathos',
    'garifalo',
    'garifalo trimeno',
    'maintanos',

    ]
};
